import re

# pattern = r'(a|b)c*'
pattern = input("Enter pattern: ")

s = input("Enter string: ")

if re.fullmatch(pattern, s):
    print("String is generated by the Regular Expression.")
else:
    print("String is NOT generated by the Regular Expression.")
